#!/usr/local/bin/bash

# Shell Prompt Color Customization.
export PS1="\\[\\033[36m\\]\\u\\[\\033[m\\]@\\[\\033[32m\\]\\h:\\[\\033[1;33m\\]\\w\\[\\033[m\\] \$ "
export CLICOLOR=1

# Add current branch to prompt.
# export GIT_PS1_SHOWDIRTYSTATE=1
# export PS1="$PS1$(echo '$(__git_ps1 "(%s)")\$ ')"

# Bash Completions from bash-completion Homebrew package.
if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
  source "$(brew --prefix)/etc/bash_completion"
fi

# For Homebrew
PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Folder for my executable Scripts
PATH="$HOME/bin:$PATH"

# Setting up Language for installed applications
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Set vim as default editor for Git.
export VISUAL=vim
export EDITOR="$VISUAL"

# Ignore duplicates in command history and increase
# history size to 1000 lines
export HISTCONTROL=ignoredups
export HISTSIZE=1000

# Don't store less history file.
export LESSHISTFILE="/dev/null"

# Java External Libraries
export CLASSPATH=".:/Users/juandaco/Programming/java/lib/*"

# For Android Development.
export GRADLE_HOME='/usr/local/opt/gradle'
export PATH=$GRADLE_HOME/bin:$PATH

# Alias file
[ -f ~/.bash_aliases ] && source ~/.bash_aliases

# Add fzf key bindings
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

export PATH="/usr/local/opt/sqlite/bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"

# Alacrity completions
source ~/.config/alacritty/alacritty-completions.bash

# cargo Rust package manager
export PATH="$HOME/.cargo/bin:$PATH"

# Add go installed binaries
export PATH="$PATH:~/go/bin"

# Add nvm path
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
