#!/usr/bin/env bash

# Force ls to output color.
alias ls='CLICOLOR_FORCE=1 ls -G'
# Force less to interpret color
alias less='less -R'
# Colorize tree and avoid diplaying node_modules
alias tree='tree -C -I node_modules'

# ls helpers
alias ll='ls -la'
alias la='ls -a'
alias l.='ll -d .*'

# Colorize grep
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

# Color coded cat
alias ccat='pygmentize -g'
alias hcat='highlight -O ansi --force'

# Run vim instead of vi.
alias vi='vim'

# Open VLC app from the command line
alias vlc='open -a VLC'

# HomeBrew update shortcut
alias upgrade="brew update && brew upgrade && brew cleanup && npm -g update && gem update"

# Top as Activity Monitor
alias ctop='top -o cpu -s 3 -n 37'
alias mtop='top -o mem -s 3 -n 37'

# Run VIM with a session
alias gvims='gvim --servername' #session-name

# Duplicate tab at same path location
alias tab='open . -a iterm'

# Chrome Debugger
alias chrome-dev='open -a "Google Chrome" --args --remote-debugging-port=9222'

# Correct error when running the Swift REPL with Python's Homebrew
alias swift='PATH="/usr/bin:$PATH" swift'

# cd to Artimo
alias artimo='cd ~/Programming/artimo/src/lap/app/'

# Rum MIT Scheme with REPL completions (add -c for file completion)
alias scheme='rlwrap -r -f "$HOME"/.scheme_repl_history scheme'

# Connect to Android Phone
alias nexus6p='adb tcpip 5555 && adb connect 192.168.1.2 && sleep 1 && adb shell'

#
alias wifi-password='security find-generic-password -wa $(ssid)'

# Source aliases not public for containing passwords
source ~/.bash_aliases_private

# Artimo queries
alias query='QUERY_PATH=/Users/juandaco/Programming/artimo-queries/; find $QUERY_PATH -name *.js -exec basename {} \; | cat "$QUERY_PATH""$(fzf)" | pbcopy'

alias stash-recover='git log --graph --oneline --decorate $(git fsck --no-reflogs | awk '\''/dangling commit/ {print $3}'\'')'

