" General configurations
runtime general.vim

" Add Plugin Configurations
runtime pluggins.vim

" Add Packages
runtime packages.vim

" Add Keyboard Mappings
runtime mappings.vim

" Autocomplete
runtime coc.vim
