#!/usr/bin/env bash
#
# Installs or updates `ripgrep`.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh" || exit 1

case "$PLATFORM" in
macos) brew_install ripgrep rg ;;
arch) pacman_install ripgrep ;;
debian | linux)
  GIT_REPO="BurntSushi/ripgrep"
  VERSION="$(github_latest_version "$GIT_REPO")" || fail "Could not find the latest version of ripgrep."

  if [ "$(installed_version rg)" != "$VERSION" ]; then
    echo "Installing ripgrep $VERSION..."

    case "$(linux_arch)" in
    arm64) TARGET="aarch64-unknown-linux-gnu" ;;
    armhf)
      # There are no ARMv6 binaries (Raspberry Pi 1 and Zero)
      [ "$(uname -m)" == "armv6l" ] && fail "The architecture armv6l is not supported yet."
      TARGET="armv7-unknown-linux-gnueabihf"
      ;;
    amd64) TARGET="x86_64-unknown-linux-musl" ;;
    *) unsupported_arch ;;
    esac

    PACKAGE_NAME="ripgrep-$VERSION-$TARGET"

    make_tmp_dir
    download "https://github.com/$GIT_REPO/releases/download/$VERSION/$PACKAGE_NAME.tar.gz" "$TMP_DIR/$PACKAGE_NAME.tar.gz"
    tar -xzf "$TMP_DIR/$PACKAGE_NAME.tar.gz" -C "$TMP_DIR" || fail "Could not extract $PACKAGE_NAME.tar.gz"
    install_bin "$TMP_DIR/$PACKAGE_NAME/rg" rg
    install_completion "$TMP_DIR/$PACKAGE_NAME/complete/rg.bash" rg
    verify_installed rg "$VERSION"
  fi
  ;;
*) unsupported_platform ;;
esac
