#!/usr/bin/env bash
#
# Installs or updates `shfmt`.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh" || exit 1

case "$PLATFORM" in
macos) brew_install shfmt ;;
arch) pacman_install shfmt ;;
debian | linux)
  GIT_REPO="mvdan/sh"
  VERSION="$(github_latest_version "$GIT_REPO")" || fail "Could not find the latest version of shfmt."

  if [ "$(installed_version shfmt)" != "$VERSION" ]; then
    echo "Installing shfmt $VERSION..."

    case "$(linux_arch)" in
    arm64) TARGET="linux_arm64" ;;
    armhf) TARGET="linux_arm" ;;
    amd64) TARGET="linux_amd64" ;;
    *) unsupported_arch ;;
    esac

    make_tmp_dir
    download "https://github.com/$GIT_REPO/releases/download/v$VERSION/shfmt_v${VERSION}_$TARGET" "$TMP_DIR/shfmt"
    install_bin "$TMP_DIR/shfmt" shfmt
    verify_installed shfmt "$VERSION"
  fi
  ;;
*) unsupported_platform ;;
esac
