#!/usr/bin/env bash
#
# Installs or updates `bat-extras`.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh" || exit 1

case "$PLATFORM" in
macos) brew_install bat-extras batman ;;
arch) pacman_install bat-extras ;;
debian | linux)
  GIT_REPO="eth-p/bat-extras"
  VERSION="$(github_latest_version "$GIT_REPO")" || fail "Could not find the latest version of bat-extras."

  if [ "$(installed_version batman)" != "$VERSION" ]; then
    echo "Installing bat-extras $VERSION..."

    make_tmp_dir
    git clone --quiet --depth 1 --branch "v$VERSION" "https://github.com/$GIT_REPO.git" "$TMP_DIR/bat-extras" 2>/dev/null ||
      fail "Could not clone bat-extras."

    # The scripts can only be minified when `shfmt` is available
    if has shfmt; then MINIFY="all"; else MINIFY="none"; fi

    (cd "$TMP_DIR/bat-extras" && ./build.sh --install --prefix="$HOME/.local" --minify "$MINIFY" --compress --no-verify) ||
      fail "Could not build bat-extras."
    verify_installed batman "$VERSION"
  fi
  ;;
*) unsupported_platform ;;
esac
