#!/usr/bin/env bash
#
# Installs or updates `tldr`.

GIT_USER="dbrgn"
GIT_REPO="tealdeer"
HOME_BIN="$HOME/bin"

OS="$(uname -s)"

if [ "$OS" == "Darwin" ]; then
  # Verify that homebrew is installed
  if [ -z "$(command -v brew)" ]; then
    echo "You need to install homebrew." 1>&2
    exit 1
  fi

  # MacOS with brew installed
  command -v tldr >>/dev/null || brew install tealdeer

elif [ "$OS" == "Linux" ]; then
  # Linux

  # Install tldr (from GitHub)
  TLDR_PACKAGE_VERSION="$(curl --silent "https://api.github.com/repos/$GIT_USER/$GIT_REPO/releases/latest" | grep '"tag_name":' | awk '{print $2}' | tr -d '",')"

  if [ -z "$(command -v tldr)" ] || [ "$(tldr --version | head -1 | awk '{print $2}')" != "$TLDR_PACKAGE_VERSION" ]; then
    pushd "$HOME_BIN" >>/dev/null || exit

    echo "Installing tldr..."

    ARCHITECTURE="$(uname -m)"

    if [ "$ARCHITECTURE" == "armv7l" ]; then
      # Raspberry Pi 3+ B
      TLDR_PACKAGE_NAME="tldr-linux-armv7-musleabihf"
    elif [ "$ARCHITECTURE" == "x86_64" ]; then
      # Linux 64bit
      TLDR_PACKAGE_NAME="tldr-linux-x86_64-musl"
    else
      # Other Architecture
      echo "The architecture $ARCHITECTURE is not supported yet." 1>&2
      exit 1
    fi

    wget --quiet --output-document=tldr "https://github.com/$GIT_USER/$GIT_REPO/releases/download/$TLDR_PACKAGE_VERSION/$TLDR_PACKAGE_NAME"
    sudo wget --quiet --output-document=/etc/bash_completion.d/tldr.bash "https://github.com/$GIT_USER/$GIT_REPO/releases/download/$TLDR_PACKAGE_VERSION/completions_bash"
    chmod u+x tldr

    if [ -n "$(command -v tldr)" ]; then
      echo "tldr correctly installed."
    else
      echo "tldr was not installed." 1>&2
    fi

    popd >>/dev/null || exit
  fi

else
  # Other OS
  echo "The OS $OS is not supported yet." 1>&2
  exit 1

fi

