#!/usr/bin/env bash
#
# Installs or updates `tldr`.

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh" || exit 1

case "$PLATFORM" in
macos) brew_install tealdeer tldr ;;
arch) pacman_install tealdeer ;;
debian | linux)
  GIT_REPO="tealdeer-rs/tealdeer"
  VERSION="$(github_latest_version "$GIT_REPO")" || fail "Could not find the latest version of tldr."

  if [ "$(installed_version tldr)" != "$VERSION" ]; then
    echo "Installing tldr $VERSION..."

    case "$(linux_arch)" in
    arm64) TARGET="linux-aarch64-musl" ;;
    armhf) TARGET="linux-arm-musleabihf" ;;
    amd64) TARGET="linux-x86_64-musl" ;;
    *) unsupported_arch ;;
    esac

    make_tmp_dir
    download "https://github.com/$GIT_REPO/releases/download/v$VERSION/tealdeer-$TARGET" "$TMP_DIR/tldr"
    download "https://github.com/$GIT_REPO/releases/download/v$VERSION/completions_bash" "$TMP_DIR/completions_bash"
    install_bin "$TMP_DIR/tldr" tldr
    install_completion "$TMP_DIR/completions_bash" tldr
    verify_installed tldr "$VERSION"
  fi
  ;;
*) unsupported_platform ;;
esac
