#!/usr/bin/env bash

OS="$(uname -s)"
NODE_VERSION=16
NODE_CODE_NAME="gallium"

if [ "$OS" == "Darwin" ]; then
  # MacOS
  if [ -z "$(command -v brew)" ]; then
    echo "You must install brew first." 1>&2
    exit 1
  fi

  if brew list | grep --quiet "node@$NODE_VERSION"; then
    brew install "node@$NODE_VERSION"

    # Install `neovim` if needed
    if [ -z "$(command -v neovim-node-host)" ]; then
      npm -g install neovim
    fi
  fi

elif [ "$OS" == "Linux" ]; then
  # Linux

  if [ -z "$(command -v node)" ]; then
    # node is not installed
    if grep --quiet arch /etc/os-release; then
      # Arch
      sudo pacman --needed -S "nodejs-lts-$NODE_CODE_NAME"
    elif grep --quiet debian /etc/os-release; then
      # Debian
      curl -sL "https://deb.nodesource.com/setup_$NODE_VERSION.x" | sudo -E bash -
      sudo apt-get install -y nodejs

      # Install `neovim` if needed
      if [ -z "$(command -v neovim-node-host)" ]; then
        sudo npm -g install neovim
      fi
    fi
  fi

else
  echo "The OS $OS is not supported." 1>&2
  exit 1

fi
