#!/usr/bin/env bash

OS="$(uname -s)"

if [ "$OS" == "Darwin" ]; then
  # MacOS
  if [ -z "$(command -v brew)" ]; then
    echo "You must install brew first." 1>&2
    exit 1
  fi

  if brew list | grep --quiet 'node@12'; then
    brew install node@12
    brew link --force --overwrite node@12

    # Install `neovim` if needed
    if [ -z "$(command -v neovim-node-host)" ]; then
      npm -g install neovim
    fi
  fi

elif [ "$OS" == "Linux" ]; then
  # Linux

  if [ -z "$(command -v node)" ]; then
    # node is not installed
    if grep --quiet arch /etc/os-release; then
      # Arch
      sudo pacman --needed -S nodejs-lts-erbium
    elif grep --quiet debian /etc/os-release; then
      # Debian
      curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Install `neovim` if needed
      if [ -z "$(command -v neovim-node-host)" ]; then
        sudo npm -g install neovim
      fi
    fi
  fi

else
  echo "The OS $OS is not supported." 1>&2
  exit 1

fi
