#!/usr/bin/env bash

mkdir -p ~/.config/tmux

ln -vf tmux.conf ~/.config/tmux/tmux.conf

TPM_DIR=~/.config/tmux/plugins/tpm
[ ! -d "$TPM_DIR" ] && git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
