#!/usr/bin/env bash
#
# Installs `vim` and `nvim` configuration files.

# Swith to dotfiles `vim` directory.
pushd "$(dirname "$0")/../vim" >/dev/null || exit 1

# Create .vim folder if it doesn't exist.
mkdir -p ~/.vim/
mkdir -p ~/.vim/tmp

# Create .config/nvim folder if it doesn't exist.
mkdir -p ~/.config/nvim/

# Link init.vim
ln -vf init.vim ~/.config/nvim/init.vim

# Link vimrc.
ln -vf vimrc ~/.vim/vimrc

# Link packages.vim
ln -vf packages.vim ~/.vim/packages.vim

# Link pluggins.vim
ln -vf pluggins.vim ~/.vim/pluggins.vim

# Link mappings.vim
ln -vf mappings.vim ~/.vim/mappings.vim

# Link functions.vim
ln -vf functions.vim ~/.vim/functions.vim

# Link functions.vim
ln -vf general.vim ~/.vim/general.vim

# ftplugin
mkdir -p ~/.vim/ftplugin
for file in ftplugin/*; do
  ln -vf "$file" "$HOME/.vim/$file"
done

# Syntax Modifications
mkdir -p ~/.vim/after/syntax
for file in syntax/*; do
  ln -vf "$file" "$HOME/.vim/after/$file"
done

# UltiSnips
mkdir -p ~/.vim/UltiSnips
for file in UltiSnips/*; do
  ln -vf "$file" "$HOME/.vim/$file"
done

# Install Package manager if not installed.
if [ ! -d ~/.vim/pack/minpac/opt/minpac ]; then
  printf "Installing Package Manager... \\n"
  mkdir -p ~/.vim/pack/minpac/opt
  cd ~/.vim/pack/minpac/opt || echo 'Failed to ' || exit
  git clone "https://github.com/k-takata/minpac"
fi

# Run vim and Install all packages.
"$EDITOR" -c "packadd minpac | source ~/.vim/packages.vim | redraw | call minpac#update('', { 'do': 'quit' })"

popd >/dev/null || exit 1
