#!/usr/bin/env bash
# shellcheck disable=2139,1090

OS="$(uname -s)"
# Force ls to output color.
if [ "$OS" == "Darwin" ]; then
  alias ls='CLICOLOR_FORCE=1 ls -G'
elif [ "$OS" == "Linux" ]; then
  alias ls='ls --color=always'
fi

# Colorize tree and avoid diplaying node_modules
alias tree='tree -C'

# ls helpers
alias ll='ls -la'
alias la='ls -a'
alias l.='ll -d .*'

# Colorize grep
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

alias kx='kubectx'

# Git
# shellcheck disable=SC2142
alias stash-recover='git log --graph --oneline --decorate $(git fsck --no-reflogs | awk '\''/dangling commit/ {print $3}'\'')'

alias copy-git-hash-HEAD='git rev-parse --short HEAD | tr -d "\n" | pbcopy'

if [ "$OS" == "Darwin" ]; then
  # HomeBrew update shortcut
  alias upgrade="brew update && brew upgrade && brew upgrade --cask && brew cleanup && npm -g update && gem update"

  # Rum MIT Scheme with REPL completions (add -c for file completion)
  alias scheme='rlwrap -r -f "$HOME"/.scheme_repl_history scheme'

  # Connect to Android Phone
  alias nexus6p='adb connect 192.168.2.182:5555 && sleep 1 && adb shell'

  # Get Wifi Password
  alias wifi-password='security find-generic-password -wa $(ssid)'
fi

# Add copy paste commands from MacOS
if [ "$OS" == "Linux" ]; then
  alias pbcopy='xsel --clipboard --input'
  alias pbpaste='xsel --clipboard --output'
fi
