# ~/.bashrc
# shellcheck disable=2148,1090

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Shell Prompt Color Customization.
export PS1="\\[\\e[01;34m\\]\\u\\[\\e[m\\]@\\[\\e[01;32m\\]\\h\\[\\e[m\\]:\\[\\e[01;33m\\]\\w\\[\\e[m\\] \\$ "
export CLICOLOR=1

# append to the history file, don't overwrite it
shopt -s histappend

#########
# MacOS #
#########
if [ "$(uname)" = "Darwin" ]; then
  # `brew` options
  if [ -n "$(command -v brew)" ]; then
    HOMEBREW_PREFIX=$(brew --prefix)
    # Bash Completions from bash-completion Homebrew package.
    [[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && source "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
  fi
fi

# Alias file
[ -f ~/.bash_aliases ] && source "$HOME/.bash_aliases"

# Bash Pre-Exec for hooks
[ -f /opt/homebrew/etc/profile.d/bash-preexec.sh ] && . /opt/homebrew/etc/profile.d/bash-preexec.sh

# fzf configurations
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# atuin configurations
command -v atuin &> /dev/null && eval "$(atuin init bash)"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# vim: ft=sh

